// <auto-generated />
using CodeFirst.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirst.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CodeFirst.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Empty")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Email = "philip@privacy.net",
                            Firstname = "Barbara",
                            Lastname = "Hall"
                        },
                        new
                        {
                            ID = 2,
                            Email = "mark@example.com",
                            Firstname = "Beryl",
                            Lastname = "Johnson"
                        },
                        new
                        {
                            ID = 3,
                            Email = "harold@yahoo.com",
                            Firstname = "Edward",
                            Lastname = "Garcia"
                        },
                        new
                        {
                            ID = 4,
                            Email = "wendy26@gmail.com",
                            Firstname = "Robert",
                            Lastname = "Peters"
                        },
                        new
                        {
                            ID = 5,
                            Email = "simon@privacy.net",
                            Firstname = "Dorothy",
                            Lastname = "Thatcher"
                        },
                        new
                        {
                            ID = 6,
                            Email = "wendy@example.com",
                            Firstname = "Donna",
                            Lastname = "Peters"
                        },
                        new
                        {
                            ID = 7,
                            Email = "sharon@example.com",
                            Firstname = "Michelle",
                            Lastname = "Anderson"
                        },
                        new
                        {
                            ID = 8,
                            Email = "edwin65@privacy.net",
                            Firstname = "Donald",
                            Lastname = "Kirby"
                        },
                        new
                        {
                            ID = 9,
                            Email = "george@msn.com",
                            Firstname = "Betty",
                            Lastname = "Hall"
                        },
                        new
                        {
                            ID = 10,
                            Email = "maria@privacy.net",
                            Firstname = "Judith",
                            Lastname = "Davidson"
                        });
                });

            modelBuilder.Entity("CodeFirst.Models.Teacher", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Teachers");
                });
#pragma warning restore 612, 618
        }
    }
}
